"""empty message

Revision ID: 24bb27f77567
Revises: d19823be07ef
Create Date: 2018-11-29 17:56:59.471085

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '24bb27f77567'
down_revision = 'd19823be07ef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todoitems', sa.Column('completed', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('todoitems', 'completed')
    # ### end Alembic commands ###
